spring.application.name=mx-address-resolver

spring.datasource.url=jdbc:postgresql://localhost:5432/mx_address_resolver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false